# Generated by Django 5.2.15 on 2026-06-20 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_display_name_user_shop_location_user_shop_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['tenant_id', 'user_id'], 'verbose_name': '企业成员', 'verbose_name_plural': '企业成员'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-created_at'], 'verbose_name': '企业/档口', 'verbose_name_plural': '企业/档口'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户账号', 'verbose_name_plural': '用户账号'},
        ),
        migrations.AlterField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.tenant', verbose_name='企业/档口'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户账号'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=120, verbose_name='企业/档口名称'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='试用到期时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='用户称呼'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop_location',
            field=models.CharField(blank=True, max_length=120, verbose_name='店铺位置'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='店铺名称'),
        ),
    ]
