# Generated by Django 5.2.15 on 2026-06-22 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_membership_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ai_daily_quota',
            field=models.IntegerField(default=5, verbose_name='AI每日次数'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ai_extra',
            field=models.IntegerField(default=0, verbose_name='AI每日扩容'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='can_ai_price',
            field=models.BooleanField(default=False, verbose_name='AI智能定价'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='can_batch',
            field=models.BooleanField(default=False, verbose_name='批量报价'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='can_compare',
            field=models.BooleanField(default=False, verbose_name='款式对比'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='can_export',
            field=models.BooleanField(default=False, verbose_name='导出Excel'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('free', '免费版'), ('pro', '专业版'), ('ultimate', '旗舰版')], default='free', max_length=20, verbose_name='会员等级'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='style_extra',
            field=models.IntegerField(default=0, verbose_name='款式扩容'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='style_quota',
            field=models.IntegerField(default=5, verbose_name='款式上限'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='team_size',
            field=models.IntegerField(default=1, verbose_name='团队人数上限'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='template_extra',
            field=models.IntegerField(default=0, verbose_name='模板扩容'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='template_quota',
            field=models.IntegerField(default=0, verbose_name='模板上限'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', '免费版'), ('pro', '专业版'), ('ultimate', '旗舰版')], max_length=20, verbose_name='会员等级')),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已过期'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='生效时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('is_extension', models.BooleanField(default=False, verbose_name='扩容包')),
                ('extension_type', models.CharField(blank=True, max_length=30, verbose_name='扩容类型')),
                ('extension_amount', models.IntegerField(default=0, verbose_name='扩容数量')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.tenant')),
            ],
            options={
                'verbose_name': '订阅记录',
                'verbose_name_plural': '订阅记录',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('ai_used', models.IntegerField(default=0, verbose_name='AI已用次数')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quotas', to='accounts.membership')),
            ],
            options={
                'verbose_name': '每日用量',
                'verbose_name_plural': '每日用量',
                'unique_together': {('membership', 'date')},
            },
        ),
    ]
