# Generated by Django 5.2.15 on 2026-06-22 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenant_ai_daily_quota_tenant_ai_extra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='方式名称')),
                ('qr_image', models.ImageField(blank=True, upload_to='payment_qr/', verbose_name='收款码图片')),
                ('instructions', models.TextField(blank=True, verbose_name='付款说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '收款方式',
                'verbose_name_plural': '收款方式',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', '免费版'), ('pro', '专业版'), ('ultimate', '旗舰版')], max_length=20, verbose_name='目标会员')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('extension_type', models.CharField(blank=True, max_length=30, verbose_name='扩容类型')),
                ('extension_amount', models.IntegerField(default=0, verbose_name='扩容数量')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已到账'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('admin_note', models.CharField(blank=True, max_length=255, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='accounts.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '付款申请',
                'verbose_name_plural': '付款申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
