# Generated by Django 5.2.15 on 2026-06-22 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_paymentmethod_paymentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_room', to='accounts.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '客服聊天室',
                'verbose_name_plural': '客服聊天室',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_staff', models.BooleanField(default=False, verbose_name='客服发送')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.supportroom')),
            ],
            options={
                'verbose_name': '客服消息',
                'verbose_name_plural': '客服消息',
                'ordering': ['created_at'],
            },
        ),
    ]
