# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_supportroom_supportmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="qr_image_data",
            field=models.TextField(blank=True, verbose_name="收款码图片数据"),
        ),
    ]
