# Generated by Django 5.2.15 on 2026-06-20 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('base', '0001_initial'),
        ('bom', '0001_initial'),
        ('styles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('material_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('process_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('packaging_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('logistics_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('other_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('profit_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('quote_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bom.bom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.currency')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheets', to='styles.style')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('material', 'Material'), ('process', 'Process'), ('packaging', 'Packaging'), ('logistics', 'Logistics'), ('other', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
                ('cost_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costing.costsheet')),
            ],
            options={
                'ordering': ['cost_sheet_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_no', models.CharField(max_length=80)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('cost_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='costing.costsheet')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'quote_no')},
            },
        ),
    ]
