# Generated by Django 5.2.15 on 2026-06-20 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_display_name_user_shop_location_user_shop_name'),
        ('costing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('fabrics', models.JSONField(blank=True, default=list)),
                ('processes', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('tenant', 'created_by', 'key')},
            },
        ),
        migrations.CreateModel(
            name='QuickStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('image_data', models.TextField(blank=True)),
                ('fabrics', models.JSONField(blank=True, default=list)),
                ('processes', models.JSONField(blank=True, default=list)),
                ('accessory_pack', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('expected_profit', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('minimum_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('quote_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('tenant', 'created_by', 'name')},
            },
        ),
    ]
