# Generated by Django 5.2.15 on 2026-06-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_quickcategory_quickstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickstyle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='styles/'),
        ),
    ]
