# Generated by Django 5.2.15 on 2026-06-20 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_membership_options_alter_tenant_options_and_more'),
        ('costing', '0003_add_image_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costitem',
            options={'ordering': ['cost_sheet_id', 'id'], 'verbose_name': '成本明细', 'verbose_name_plural': '成本明细'},
        ),
        migrations.AlterModelOptions(
            name='costsheet',
            options={'ordering': ['-created_at'], 'verbose_name': '成本单', 'verbose_name_plural': '成本单'},
        ),
        migrations.AlterModelOptions(
            name='quickcategory',
            options={'ordering': ['created_at'], 'verbose_name': '用户品类模板', 'verbose_name_plural': '用户品类模板'},
        ),
        migrations.AlterModelOptions(
            name='quickstyle',
            options={'ordering': ['-updated_at'], 'verbose_name': '快速算价款式', 'verbose_name_plural': '快速算价款式'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': '报价单', 'verbose_name_plural': '报价单'},
        ),
        migrations.AlterField(
            model_name='costitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='costitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant', verbose_name='企业/档口'),
        ),
        migrations.AlterField(
            model_name='costsheet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='costsheet',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant', verbose_name='企业/档口'),
        ),
        migrations.AlterField(
            model_name='quickcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='quickcategory',
            name='description',
            field=models.CharField(blank=True, max_length=160, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='quickcategory',
            name='fabrics',
            field=models.JSONField(blank=True, default=list, verbose_name='默认面料'),
        ),
        migrations.AlterField(
            model_name='quickcategory',
            name='key',
            field=models.CharField(max_length=80, verbose_name='模板标识'),
        ),
        migrations.AlterField(
            model_name='quickcategory',
            name='name',
            field=models.CharField(max_length=80, verbose_name='品类名称'),
        ),
        migrations.AlterField(
            model_name='quickcategory',
            name='processes',
            field=models.JSONField(blank=True, default=list, verbose_name='默认工序'),
        ),
        migrations.AlterField(
            model_name='quickcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant', verbose_name='企业/档口'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='accessory_pack',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='辅料包装费'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='category',
            field=models.CharField(blank=True, max_length=80, verbose_name='品类'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='expected_profit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='期望利润'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='fabrics',
            field=models.JSONField(blank=True, default=list, verbose_name='面料明细'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='styles/', verbose_name='图片文件'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='image_data',
            field=models.TextField(blank=True, verbose_name='图片数据'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='minimum_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='最低接单价'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='name',
            field=models.CharField(max_length=120, verbose_name='款式名称'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='processes',
            field=models.JSONField(blank=True, default=list, verbose_name='工序明细'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='profit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='单件利润'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='quote_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='建议报价'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant', verbose_name='企业/档口'),
        ),
        migrations.AlterField(
            model_name='quickstyle',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='单件成本'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant', verbose_name='企业/档口'),
        ),
    ]
