# Generated by Django 5.2.15 on 2026-06-20 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_membership_options_alter_tenant_options_and_more'),
        ('costing', '0004_alter_costitem_options_alter_costsheet_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiProviderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='DeepSeek', max_length=80, verbose_name='配置名称')),
                ('provider', models.CharField(default='deepseek', max_length=40, verbose_name='服务商')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API 密钥')),
                ('base_url', models.URLField(default='https://api.deepseek.com', verbose_name='接口地址')),
                ('model', models.CharField(default='deepseek-v4-flash', max_length=80, verbose_name='模型名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'AI 助手配置',
                'verbose_name_plural': 'AI 助手配置',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AiChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI 助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('intent', models.CharField(blank=True, max_length=40, verbose_name='意图')),
                ('cost_draft', models.JSONField(blank=True, default=dict, verbose_name='款式/成本草稿')),
                ('calculation', models.JSONField(blank=True, default=dict, verbose_name='计算结果')),
                ('need_more_info', models.BooleanField(default=False, verbose_name='是否需要补充信息')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant', verbose_name='企业/档口')),
            ],
            options={
                'verbose_name': 'AI 聊天记录',
                'verbose_name_plural': 'AI 聊天记录',
                'ordering': ['created_at'],
            },
        ),
    ]
